#!/usr/bin/env zsh

TNCLI_COMMAND='just -f ~/.tn/cli/justfile -d .'
alias tn=$TNCLI_COMMAND

_tncli_completion() {
    local options
    options="$(eval $TNCLI_COMMAND --summary)"
    local -a options_array=(${(s: :)options})
    _describe 'options' options_array
}
compdef _tncli_completion tn=$TNCLI_COMMAND
setopt complete_aliases
